version: "3.9"

services:
  safereport_api:
    build: .
    container_name: safereport_api
    command: gunicorn --bind 0.0.0.0:80 --workers 4 --worker-class uvicorn.workers.UvicornWorker app.main:app
    expose:
      - "80"
    volumes:
      - .:/app
    depends_on:
      - safereport_redis
    environment:
      REDIS_HOST: safereport_redis
      REDIS_PORT: 6379
    networks:
      - safereport_network

  safereport_worker:
    build: .
    container_name: safereport_worker
    command: celery -A app.tasks:app worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - safereport_redis
    networks:
      - safereport_network

  safereport_beat:
    build: .
    container_name: safereport_beat
    command: celery -A app.tasks:app beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - safereport_redis
    networks:
      - safereport_network

  safereport_redis:
    image: redis:7-alpine
    container_name: safereport_redis
    ports:
      - "6379:6379"
    volumes:
      - safereport_redis_volume_data:/data
    networks:
      - safereport_network

  safereport_nginx:
    image: nginx:latest
    container_name: safereport_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
    depends_on:
      - safereport_api
    networks:
      - safereport_network

volumes:
  safereport_redis_volume_data:
    name: safereport_redis_volume

networks:
  safereport_network:
    name: safereport_network
