name: CI/CD SafeReport API

on:
  push:
    branches:
      - main 

jobs:
  deploy_safereport_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: üöÄ Executar Deploy Remoto (Pull e Build no Droplet)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            # 1. Instala o plugin 'docker compose'
            sudo apt-get update && sudo apt-get install docker-compose-plugin -y
            
            # 2. Navega at√© o diret√≥rio de deploy
            DEPLOY_PATH="/srv/safereport-api"
            cd $DEPLOY_PATH
            
            # 3. Puxa o c√≥digo mais recente
            git pull origin main
            
            # 4. Parar e remover containers antigos
            docker compose down
            
            # 5. Construir a nova imagem e subir os servi√ßos
            docker compose up -d --build --force-recreate
            
            echo "Deploy e constru√ß√£o conclu√≠dos no Droplet!"